package strategy

import (
	"fmt"
	"go-trading-bot/exchange"
)

// Signal represents an actionable trading signal generated by a strategy.
type Signal string

const (
	SignalBuy  Signal = "buy"
	SignalSell Signal = "sell"
	SignalHold Signal = "hold"
)

// Strategy defines the interface for trading algorithms.
type Strategy interface {
	CalculateSignal(ticker *exchange.Ticker) (Signal, error)
}

// DummyStrategy is a simple implementation for testing purposes.
type DummyStrategy struct {
	// Add parameters here later, like moving average periods, etc.
}

// NewDummyStrategy creates a new DummyStrategy.
func NewDummyStrategy() *DummyStrategy {
	return &DummyStrategy{}
}

// CalculateSignal generates a random or fixed signal for testing.
func (s *DummyStrategy) CalculateSignal(ticker *exchange.Ticker) (Signal, error) {
	fmt.Printf("DummyStrategy: Evaluating signal for %s at price %f\n", ticker.Pair, ticker.Price)
	// For testing, just return hold
	return SignalHold, nil
}
